# Generated by Django 2.2.5 on 2020-09-22 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200922_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsholder',
            old_name='seats',
            new_name='tickets',
        ),
        migrations.AlterField(
            model_name='ticketsholder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
