# Generated by Django 2.2.5 on 2020-09-22 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200922_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsholder',
            name='tickets',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
