# Generated by Django 2.2.5 on 2020-09-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200922_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
