# Generated by Django 2.2.5 on 2020-09-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsholder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event'),
        ),
    ]
