# Generated by Django 2.2.5 on 2020-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200922_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
